version: '3.1'

services:

  db:
    image: mariadb:11.5.2
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
    logging:
      options:
        max-size: "10m"
    volumes:
      - ./tmpdata/mysql:/var/lib/mysql