syntax = "proto3";

package IT.WebServices.Fragments.Dashboard;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "Protos/IT/WebServices/Fragments/Dashboard/DashboardMetrics.proto";

service DashboardInterface {
	rpc GetKpis (GetKpisRequest) returns (GetKpisResponse) {
		option (google.api.http) = {
			get: "/api/admin/dashboard"
		};
	}
}

message GetKpisRequest {}

message GetKpisResponse {
	UserKpis Users = 1;
	SubscriptionKpis Subscriptions = 2;
	google.protobuf.Timestamp AsOfUTC = 3;
	ContentKpis Content = 4;
}
