syntax = "proto3";

package IT.WebServices.Fragments.Authorization.Payment.Stripe;

import "google/api/annotations.proto";
import "Protos/IT/WebServices/Fragments/Authorization/Payment/DataRecords.proto";

service StripeInterface {
  rpc StripeFinishOwnSubscription (StripeFinishOwnSubscriptionRequest) returns (StripeFinishOwnSubscriptionResponse)
  {
    option (google.api.http) = {
      post: "/api/payment/stripe/subscription/finish"
      body: "*"
    };
  }

  rpc StripeFinishUpdateOwnCard (StripeFinishUpdateOwnCardRequest) returns (StripeFinishUpdateOwnCardResponse)
  {
    option (google.api.http) = {
      post: "/api/payment/stripe/subscription/updatecard/finish"
      body: "*"
    };
  }

  rpc StripeStartUpdateOwnCard (StripeStartUpdateOwnCardRequest) returns (StripeStartUpdateOwnCardResponse)
  {
    option (google.api.http) = {
      post: "/api/payment/stripe/subscription/updatecard"
      body: "*"
    };
  }
}

message StripeEnsureOneTimeProductRequest {
	string InternalID = 1;
	string Name = 2;
	uint32 MinimumPrice = 11;
	uint32 MaximumPrice = 12;
}

message StripeEnsureOneTimeProductResponse {
	string Error = 1;
}

message StripeFinishOwnSubscriptionRequest {
  string ProcessorSessionID = 1;
}

message StripeFinishOwnSubscriptionResponse {
  GenericSubscriptionRecord Record = 1;
  string Error = 2;
}

message StripeFinishUpdateOwnCardRequest {
  string InternalSubscriptionID = 1;
  string ProcessorSessionID = 2;
}

message StripeFinishUpdateOwnCardResponse {
  GenericSubscriptionRecord Record = 1;
  string Error = 2;
}

message StripeStartUpdateOwnCardRequest {
  string InternalSubscriptionID = 1;
  string SuccessUrl = 11;
  string CancelUrl = 12;
}

message StripeStartUpdateOwnCardResponse {
  string PaymentLink = 1;
  string Error = 2;
}
