syntax = "proto3";

package IT.WebServices.Fragments.Authorization.Discord;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";
import "Protos/IT/WebServices/Fragments/Errors.proto";
import "Protos/IT/WebServices/Fragments/Authorization/Discord/DiscordRecords.proto";

service DiscordInterface {
	rpc CreateMemberRecord (CreateMemberRecordRequest) returns (CreateMemberRecordResponse) {
		option (google.api.http) = {
			post: "/api/discord/member",
			body: "*"
		};
	};
	rpc ModifyMemberRecord (ModifyMemberRecordRequest) returns (ModifyMemberRecordResponse) {
		option (google.api.http) = {
			post: "/api/discord/member/{UserId}",
			body: "*"
		};
	};
	rpc GetMemberByUserId (GetMemberByUserIdRequest) returns (GetMemberResponse) {
		option (google.api.http) = {
			get: "/api/discord/member/{UserId}"
		};
	};
	rpc GetMemberByDiscordId (GetMemberByDiscordIdRequest) returns (GetMemberResponse) {
		option (google.api.http) = {
			get: "/api/discord/member/discordid/{DiscordUserId}"
		};
	};
	rpc GetMembers (GetMembersRequest) returns (GetMembersResponse) {
		option (google.api.http) = {
			get: "/api/discord/member"
		};
	};
	rpc BanMember (BanMemberRequest) returns (BanMemberResponse) {
		option (google.api.http) = {
			post: "/api/discord/member/{UserId}/ban",
			body: "*"
		};
	};
	rpc ShunDiscordMember (ShunDiscordMemberRequest) returns (ShunDiscordMemberResponse) {
		option (google.api.http) = {
			post: "/api/discord/member/{UserId}/shun",
			body: "*"
		};
	};
	rpc UnShunDiscordMember (UnShunDiscordMemberRequest) returns (UnShunDiscordMemberResponse) {
		option (google.api.http) = {
			post: "/api/discord/member/{UserId}/unshun",
			body: "*"
		};	
	};
	rpc GetShuns (GetShunsRequest) returns (GetShunsResponse) {
		option (google.api.http) = {
			get: "/api/discord/member/{UserId}/shun"
		};	
	};
	rpc CreateTicket (CreateTicketRequest) returns (CreateTicketResponse) {
		option (google.api.http) = {
			post: "/api/discord/ticket",
			body: "*"
		};
	};
	rpc AddTicketMessage (AddTicketMessageRequest) returns (AddTicketMessageResponse) {
		option (google.api.http) = {
			post: "/api/discord/ticket/{TicketId}",
			body: "*"
		};
	};
	rpc CloseTicket (CloseTicketRequest) returns (CloseTicketResponse) {
		option (google.api.http) = {
			post: "/api/discord/ticket/{TicketId}/close",
			body: "*"
		};
	};
	rpc GetTickets (GetTicketsRequest) returns (GetTicketsResponse) {
		option (google.api.http) = {
			get: "/api/discord/ticket",
		};
	};
}

message CreateMemberRecordRequest {
	string UserId = 1;																// References the UserRecord.UserID property
	string DiscordUserId = 2;												// User's Discord Account Global Id
	string DiscordUserName = 3;											// User's Discord Account Global UserName
	uint32 CurrentLevelCents = 4;											// References The Amount the User Is Subscribed For
	google.protobuf.Timestamp ExpiresOnUTC = 5;				// References The DateTimeUTC This Subscription Expires
	string InternalSubscriptionId = 6;									// Reference To The User's Internal Subscription Record (If Any)
	repeated string Tiers = 7;												// Stores the Subscription Tiers That Apply To This User
}

message CreateMemberRecordResponse {
	DiscordMemberRecord Record = 1;
	APIError Error = 2;
}

message ModifyMemberRecordRequest {
	string UserId = 1;																// References The UserRecord.UserID property
	DiscordMemberRecord Record = 2;								// Record Of The Member To Modify
}

message ModifyMemberRecordResponse {
	DiscordMemberRecord Record = 1;
	APIError Error = 2;
}

message GetMemberByUserIdRequest {
	string UserId = 1;
}

message GetMemberByDiscordIdRequest {
	string DiscordUserId = 1;
}

message GetMemberResponse {
	DiscordMemberRecord Record = 1;
	APIError Error = 2;
}

message GetMembersRequest {
	string PossibleUserIds = 1;
	string PossibleUserDiscordIds = 2; // TODO: Remove
	bool IncludeShunned = 3;		// TODO: Remove
	bool IncludeBanned = 4;
	uint32 PageSize = 5;
	uint32 PageOffset = 6;
	google.protobuf.Timestamp ExpiredOnUTC = 7; // TODO: Remove
}

message GetMembersResponse {
	repeated DiscordMemberRecord Record = 1;
	uint32 PageTotalItems = 2;
	uint32 PageOffsetStart = 3;
	uint32 PageOffsetEnd = 4;
	APIError Error = 5;
}

message BanMemberRequest {
	string UserId = 1;																// References the UserRecord.UserID property
	string BannedByDiscordId = 2;									   // Banning User's Discord Account Global Id
	string BannedReason = 3;
}

message BanMemberResponse {
	APIError Error = 1;
}

message ShunDiscordMemberRequest {
	string UserId = 1;																// References the UserRecord.UserID property
	string ShunnedByDiscordId = 2;										// Discord Id of the Mod/Admin Invoking the Shun
	string Reason = 3;
}

message ShunDiscordMemberResponse {
	DiscordShunRecord Record = 1;
	APIError Error = 2;
}

message UnShunDiscordMemberRequest {
	string UserId = 1;																// References the UserRecord.UserID property
	string ShunId = 2;																// References the DiscordShunRecord.ShunId property
	string UnShunnedByDiscordId = 3;									// Discord Id of the Mod/Admin Invoking the UnShun
}

message UnShunDiscordMemberResponse {
	APIError Error = 1;
}

message GetShunsRequest {
	string UserId = 1;
	bool IncludeInactive = 2;
	uint32 PageSize = 3;
	uint32 PageOffset = 4;
}

message GetShunsResponse {
	repeated DiscordShunRecord Records = 1;
	uint32 PageTotalItems = 2;
	uint32 PageOffsetStart = 3;
	uint32 PageOffsetEnd = 4;
	APIError Error = 5;
}

message CreateTicketRequest {
	string UserId = 1;																// References The UserRecord.UserID property
	string Subject = 2;
	string Text = 3;
}

message CreateTicketResponse {
	DiscordTicketRecord Record = 1;
	APIError Error = 2;
}

message AddTicketMessageRequest {
	string TicketId = 1;															// References The DiscordTicketRecord.TicketId property
	string UserId = 2;																// References The UserRecord.UserID property (if sender is a platform user)
	string SentByDiscordId = 3;											// Discord ID of the User Sending the Message
	string Text = 4;
}

message AddTicketMessageResponse {
	DiscordTicketThreadMessage Record = 1;
	APIError Error = 2;
}

message CloseTicketRequest {
	string TicketId = 1;
	string ClosedByDiscordId = 2;										// Discord ID of the Mod/Admin Closing the Ticket
}

message CloseTicketResponse {
	DiscordTicketRecord Record = 1;
	APIError Error = 2;
}

message GetTicketsRequest {
	bool IncludeClosed = 1;
	string UserId = 2;
	uint32 PageSize = 3;
	uint32 PageOffset = 4;
}

message GetTicketsResponse {
	repeated DiscordTicketRecord Records = 1;
	uint32 PageTotalItems = 2;
	uint32 PageOffsetStart = 3;
	uint32 PageOffsetEnd = 4;
	APIError Error = 5;
}
