syntax = "proto3";

package IT.WebServices.Fragments.Merch;

import "google/protobuf/timestamp.proto";
import "Protos/IT/WebServices/Fragments/Merch/SharedMerchTypes.proto";

message GenericMerchRecord {
  string InternalProductId = 1;
  string InternalStoreId = 2;
  MerchRecordProvider Provider = 4;
  string ProcessorProductId = 5;

  string SKU = 11;
  uint32 PriceCents = 12;
  uint32 CompareAtPriceCents = 13;
  string Title = 14;
  string Description = 15;
  string Vendor = 16;
  string ProductType = 17;
  string Url = 18;

  GenericMerchImageRecord FeaturedImage = 21;
  repeated GenericMerchImageRecord OtherImages = 22;
  repeated string Tags = 23;
  repeated GenericMerchVariantRecord Variants = 24;
  bool InStock = 25;

  google.protobuf.Timestamp CreatedOnUTC = 51;
  google.protobuf.Timestamp ModifiedOnUTC = 52;
  google.protobuf.Timestamp PublishOnUTC = 53;
}

message GenericMerchVariantRecord {
  string ProcessorVariantId = 1;
  string SKU = 2;
  uint32 PriceCents = 3;
  uint32 CompareAtPriceCents = 4;
  bool InStock = 5;
  repeated GenericMerchVariantOption Options = 6;
  GenericMerchImageRecord Image = 7;
}

message GenericMerchVariantOption {
  string Name = 1;   // e.g. "Size", "Color"
  string Value = 2;  // e.g. "Large", "Red"
}

message GenericMerchImageRecord {
  string ImageAssetID = 1;
  string AltText = 2;
  string Url = 3;
}
