syntax = "proto3";

package IT.WebServices.Fragments.Authorization.Events;

import "google/api/annotations.proto";
import "Protos/IT/WebServices/Fragments/Errors.proto";
import "Protos/IT/WebServices/Fragments/Authorization/Events/DataRecords.proto";

service EventInterface {
	rpc GetEvents (GetEventsRequest) returns (GetEventsResponse) {
		option (google.api.http) = {
			get: "/api/events"
		};
	}

	rpc GetEvent (GetEventRequest) returns (GetEventResponse) {
		option (google.api.http) = {
			get: "/api/events/{EventID}"
		};
	}

	rpc GetOwnTickets (GetOwnTicketsRequest) returns (GetOwnTicketsResponse) {
		option (google.api.http) = {
			get: "/api/events/user/tickets"
		};
	}

	rpc ReserveTicket (ReserveTicketRequest) returns (ReserveTicketResponse) {
		option (google.api.http) = {
			post: "/api/events/{EventID}/tickets/reserve"
			body: "*"
		};
	}
}

message GetEventsRequest {
	uint32 PageSize = 10;
	uint32 PageOffset = 11;
}

message GetEventsResponse {
	repeated GenericEventRecord Records = 1;
	uint32 PageOffsetStart = 10;
	uint32 PageOffsetEnd = 11;
	uint32 PageTotalItems = 12;
	APIError Error = 13;
}

message GetEventRequest {
	string EventID = 1;
}

message GetEventResponse {
	GenericEventRecord Record = 1;
	APIError Error = 2;
}

message GetOwnTicketsRequest {
	uint32 PageSize = 10;
	uint32 PageOffset = 11;
}

message GetOwnTicketsResponse {
	repeated GenericEventTicketRecord Records = 1;
	uint32 PageOffsetStart = 10;
	uint32 PageOffsetEnd = 11;
	uint32 PageTotalItems = 12;
	APIError Error = 13;
}

message ReserveTicketRequest {
	string EventID = 1;
	string TicketClassID = 2;
	uint32 Quantity = 3;
}

message ReserveTicketResponse {
	repeated GenericEventTicketRecord Tickets = 1;
	string CheckoutUrl = 2;
	APIError Error = 3;
}