syntax = "proto3";

package IT.WebServices.Fragments.Careers;
import "google/api/annotations.proto";
import "buf/validate/validate.proto";
import "Protos/IT/WebServices/Fragments/Errors.proto";
import "Protos/IT/WebServices/Fragments/Careers/CareersRecord.proto";

service CareersInterface {
	rpc CreateCareer(CreateCareerRequest) returns (CreateCareerResponse) {
		option (google.api.http) = {
			post: "/api/admin/careers"
			body: "*"
		};
	}

	rpc GetCareer(GetCareerRequest) returns (GetCareerResponse) {
		option (google.api.http) = {
			get: "/api/careers/{CareerId}"
		};
	}

	rpc ListCareers(ListCareersRequest) returns (ListCareersResponse) {
		option (google.api.http) = {
			get: "/api/careers"
		};
	}

	rpc AdminListCareers(AdminListCareersRequest) returns (ListCareersResponse) {
		option (google.api.http) = {
			get: "/api/admin/careers"
		};
	}

	rpc UpdateCareer(UpdateCareerRequest) returns (UpdateCareerResponse) {
		option (google.api.http) = {
			put: "/api/admin/careers/{CareerId}"
			body: "*"
		};
	}

	rpc DeleteCareer(DeleteCareerRequest) returns (DeleteCareerResponse) {
		option (google.api.http) = {
			delete: "/api/admin/careers/{CareerId}"
		};
	}
}

message CreateCareerRequest {
	string Title = 1 [(buf.validate.field).string.min_len = 3];
	string Company = 2 [(buf.validate.field).string.min_len = 3];
	ListingLocation Location = 3 [(buf.validate.field).required = true];
	string ReportsTo = 4[(buf.validate.field).required = true];
	string Contact = 5[(buf.validate.field).required = true];
	string About = 6 [(buf.validate.field).string.min_len = 10];
	string RoleOverview = 7 [(buf.validate.field).string.min_len = 10];
	repeated string Responsibilities = 8 [(buf.validate.field).repeated.min_items = 1];
	repeated string Qualifications = 9 [(buf.validate.field).repeated.min_items = 1];
	repeated WeeklyDeliverable WeeklyDeliverables = 10;
}

message CreateCareerResponse {
	string CareerId = 1;
	APIError  Error = 2;
}

message GetCareerRequest {
	string CareerId = 1 [(buf.validate.field).string.uuid = true];
}

message GetCareerResponse {
	CareerRecord Career = 1;
	APIError Error = 2;
}

message ListCareersRequest {
	uint32 PageSize = 1;
	uint32 PageOffset = 2;
}

message AdminListCareersRequest {
	uint32 PageSize = 1;
	uint32 PageOffset = 2;
	bool IncludeDeleted = 3;
}

message ListCareersResponse {
	repeated CareerListRecord Careers = 1;
	uint32 PageSize = 2;
	uint32 PageOffsetStart = 3;
	uint32 PageOffsetEnd = 4;
	uint32 PageTotalItems = 5;
	APIError Error = 10;
}

message UpdateCareerRequest {
	string CareerId = 1 [(buf.validate.field).string.uuid = true];
	CareerRecord Career = 2 [(buf.validate.field).required = true];
}

message UpdateCareerResponse {
	CareerRecord Record = 1;
	APIError Error = 2;
}

message DeleteCareerRequest {
	string CareerId = 1 [(buf.validate.field).string.uuid = true];
}

message DeleteCareerResponse {
	APIError Error = 1;
}